import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "routes/login.tsx"),
  route("public/fdj-hesperia", "./routes/fdj-hesperia-public.tsx"),
  route("public/vq-balance-sheet", "./routes/vq-balance-sheet-public.tsx"),
  route("public/bf-access", "./routes/bf-access-public.tsx"),
  route("public/bf-access/profit-loss", "./routes/quickbooks-profit-loss.tsx", { id: "public-profit-loss" }),
  route("public/bf-access/balance-sheet", "./routes/quickbooks-balance-sheet.tsx", { id: "public-balance-sheet" }),
  route("public/bf-access/trial-balance", "./routes/quickbooks-trial-balance.tsx", { id: "public-trial-balance" }),
  route("public/bf-access/general-ledger", "./routes/quickbooks-general-ledger.tsx", { id: "public-general-ledger" }),
  route("legal/terms", "./routes/legal-terms.tsx"),
  route("legal/privacy", "./routes/legal-privacy.tsx"),
  layout("routes/app-layout.tsx", [
    index("routes/home.tsx"),
route("assets", "routes/assets.tsx"),
    route("assets/:id", "routes/asset-detail.tsx"),
    route("notes", "routes/notes.tsx"),
    route("agents", "routes/agents.tsx"),
    route("agents/:id", "routes/agent-chat.tsx"),
    route("office", "routes/office.tsx"),
    route("tools", "routes/calculations.tsx"),
    route("tools/developer-payment", "routes/calc-dev-payment.tsx"),
    route("tools/property-analysis", "routes/calc-property-analysis.tsx"),
    route("tools/fdj-hesperia", "./routes/fdj-hesperia.tsx"),
    route("tools/fdj-hesperia/financials", "./routes/fdj-hesperia-financials.tsx"),
    route("tools/fdj-hesperia/documents", "./routes/fdj-hesperia-documents.tsx"),
    route("tools/fdj-hesperia/advisory", "./routes/fdj-hesperia-advisory.tsx"),
    route("tools/fdj-hesperia/tax", "./routes/fdj-hesperia-tax.tsx"),
    route("tools/penguin-nyc", "./routes/penguin-nyc.tsx"),
    route("tools/penguin-nyc/advisory", "./routes/penguin-nyc-advisory.tsx"),
    route("tools/penguin-nyc/clauses", "./routes/penguin-nyc-clauses.tsx"),
    route("tools/ceo-agreement", "./routes/ceo-agreement.tsx"),
    route("tools/quickbooks", "./routes/quickbooks.tsx"),
    route("tools/quickbooks/profit-loss", "./routes/quickbooks-profit-loss.tsx"),
    route("tools/quickbooks/balance-sheet", "./routes/quickbooks-balance-sheet.tsx"),
    route("tools/quickbooks/trial-balance", "./routes/quickbooks-trial-balance.tsx"),
    route("tools/quickbooks/general-ledger", "./routes/quickbooks-general-ledger.tsx"),
    route("settings", "./routes/settings.tsx"),
    route("estate-map", "./routes/estate-map.tsx"),
    route("tools/ledger-louise", "./routes/ledger-louise.tsx"),
    route("tools/vq-balance-sheet", "./routes/vq-balance-sheet.tsx"),
  ]),
] satisfies RouteConfig;
