import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("login", "routes/login.tsx"),
  route("complete-profile", "routes/complete-profile.tsx"),
  route("public/fdj-hesperia", "./routes/fdj-hesperia-public.tsx"),
  route("public/vq-balance-sheet", "./routes/vq-balance-sheet-public.tsx"),
  route("public/bf-access", "./routes/bf-access-public.tsx"),
  route("public/bf-access/profit-loss", "./routes/quickbooks-profit-loss.tsx", { id: "public-profit-loss" }),
  route("public/bf-access/balance-sheet", "./routes/quickbooks-balance-sheet.tsx", { id: "public-balance-sheet" }),
  route("public/bf-access/trial-balance", "./routes/quickbooks-trial-balance.tsx", { id: "public-trial-balance" }),
  route("public/bf-access/general-ledger", "./routes/quickbooks-general-ledger.tsx", { id: "public-general-ledger" }),
  route("legal/terms", "./routes/legal-terms.tsx"),
  route("legal/privacy", "./routes/legal-privacy.tsx"),
  layout("routes/app-layout.tsx", [
    route("home", "routes/home.tsx"),
    route("assets", "routes/assets.tsx"),
    route("assets/:id", "routes/asset-detail.tsx"),
    route("assets/:id/contract/:contractId", "routes/contract-pdf.tsx"),
    route("msas", "routes/msas.tsx"),
    route("notes", "routes/notes.tsx"),
    route("office", "routes/office.tsx"),
    route("tools", "routes/calculations.tsx"),
    route("tools/developer-payment", "routes/calc-dev-payment.tsx"),
    route("tools/property-analysis", "routes/calc-property-analysis.tsx"),
    route("tools/fdj-hesperia", "./routes/fdj-hesperia.tsx"),
    route("tools/fdj-hesperia/financials", "./routes/fdj-hesperia-financials.tsx"),
    route("tools/fdj-hesperia/documents", "./routes/fdj-hesperia-documents.tsx"),
    route("tools/fdj-hesperia/advisory", "./routes/fdj-hesperia-advisory.tsx"),
    route("tools/fdj-hesperia/tax", "./routes/fdj-hesperia-tax.tsx"),
    route("tools/ceo-agreement", "./routes/ceo-agreement.tsx"),
    route("tools/taxes", "./routes/taxes.tsx"),
    route("settings", "./routes/settings.tsx"),
    route("users", "./routes/users.tsx"),
    route("treasury", "./routes/treasury.tsx"),
    route("books/transactions", "./routes/books-transactions.tsx"),
    route("books/review", "./routes/books-review.tsx"),
    route("books/reports", "./routes/books-reports.tsx"),
    route("books/reports/cell", "./routes/books-cell.tsx"),
    route("books/vendors", "./routes/books-vendors.tsx"),
    route("books/vendors/detail", "./routes/books-vendor-detail.tsx"),
    route("books/loans", "./routes/books-loans.tsx"),
    route("treasury/mappings", "./routes/treasury-mappings.tsx"),
    route("treasury/:accountId", "./routes/treasury-account.tsx"),
    route("notifications", "./routes/notifications.tsx"),
    route("estate-map", "./routes/estate-map.tsx"),
    route("tools/ledger-louise", "./routes/ledger-louise.tsx"),
    route("tools/vq-balance-sheet", "./routes/vq-balance-sheet.tsx"),
  ]),
] satisfies RouteConfig;
