import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("login", "routes/login.tsx"),
  route("complete-profile", "routes/complete-profile.tsx"),
  route("public/fdj-hesperia", "./routes/fdj-hesperia-public.tsx"),
  route("public/vq-balance-sheet", "./routes/vq-balance-sheet-public.tsx"),
  route("legal/terms", "./routes/legal-terms.tsx"),
  route("legal/privacy", "./routes/legal-privacy.tsx"),
  layout("routes/app-layout.tsx", [
    route("home", "routes/home.tsx"),
    route("assets", "routes/assets.tsx"),
    route("assets/:id", "routes/asset-detail.tsx"),
    route("assets/:id/contract/:contractId", "routes/contract-pdf.tsx"),
    route("msas", "routes/msas.tsx"),
    route("notes", "routes/notes.tsx"),
    route("office", "routes/office.tsx"),
    route("settings", "./routes/settings.tsx"),
    route("users", "./routes/users.tsx"),
    route("treasury", "./routes/treasury.tsx"),
    route("investments", "./routes/investments.tsx"),
    route("books/transactions", "./routes/books-transactions.tsx"),
    route("books/review", "./routes/books-review.tsx"),
    route("books/calendar", "./routes/books-calendar.tsx"),
    route("books/reports", "./routes/books-reports.tsx"),
    route("books/reports/cell", "./routes/books-cell.tsx"),
    route("books/vendors", "./routes/books-vendors.tsx"),
    route("books/vendors/detail", "./routes/books-vendor-detail.tsx"),
    route("books/rules", "./routes/books-rules.tsx"),
    route("books/loans", "./routes/books-loans.tsx"),
    route("treasury/mappings", "./routes/treasury-mappings.tsx"),
    route("treasury/:accountId", "./routes/treasury-account.tsx"),
    route("notifications", "./routes/notifications.tsx"),
    route("estate-map", "./routes/estate-map.tsx"),
  ]),
] satisfies RouteConfig;
